name: Run Tests

on: push

jobs:
  build:
    env:
      PIPELINE_CONTEXT: DEV
      PIPELINE_LIBRARY_PATH: ${{ github.workspace }}/.github/library

    steps:
      - name: Checkout source Git repo
        uses: actions/checkout@v3

      - name: Stable with rustfmt and clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      
      - name: Install cargo-audit binary crate
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true

      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
